[Game-Settings]

[Editor-Settings]
undo-history-limit = 200
master-volume = 0.5
seen-tutorial = false
allow-grid-rotation = false # sane people probably don't care about rotating the grid
scroll-sensitivity = 3.0

# keybinds can have multiple options, seperated with " | "
[Keybinds]
Save  = 'Ctrl+S'
Undo  = 'Ctrl+Z'
Redo  = 'Ctrl+Shift+Z | Ctrl+Y'
Cut   = 'Ctrl+X'
Copy  = 'Ctrl+C'
Paste = 'Ctrl+V'


